apiVersion: v1
kind: Secret
metadata:
  name: auth-db-secret
  namespace: tech-challenge
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@tech-challenge-auth-db.cxd2hyzinbx9.us-east-1.rds.amazonaws.com:5432/postgres"
  MASTER_KEY: "tech-challenge-master-key-2024"

---
apiVersion: v1
kind: Secret
metadata:
  name: flag-db-secret
  namespace: tech-challenge
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@tech-challenge-flag-db.cxd2hyzinbx9.us-east-1.rds.amazonaws.com:5432/postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: targeting-db-secret
  namespace: tech-challenge
type: Opaque
stringData:
  DATABASE_URL: "postgres://postgres:postgres@tech-challenge-targeting-db.cxd2hyzinbx9.us-east-1.rds.amazonaws.com:5432/postgres"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: tech-challenge
type: Opaque
stringData:
  REDIS_URL: "rediss://master.tech-challenge-redis.22dkyv.use1.cache.amazonaws.com:6379"

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: tech-challenge
type: Opaque
stringData:
  AWS_REGION: "us-east-1"
  AWS_SQS_URL: "https://sqs.us-east-1.amazonaws.com/590414915864/tech-challenge-events"
  AWS_DYNAMODB_TABLE: "tech-challenge-analytics"